### GET tasksById
GET http://localhost:8080/api/v1/tasks/123

### GET tasksById notFound
GET http://localhost:8080/api/v1/tasks/12333

### GET listAll
GET http://localhost:8080/api/v1/tasks

### DELETE deleteBtId
DELETE http://localhost:8080/api/v1/tasks/123

### POST createTask
POST http://localhost:8080/api/v1/tasks
Content-Type: application/json

{
  "description": "asdfa",
  "completed": false
}

### PUT update
PUT http://localhost:8080/api/v1/tasks/123
Content-Type: application/json

{
  "description": "123 updated",
  "completed": true
}
